name: Release
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go
      - uses: actions/checkout@v2
      - name: Prepare env
        run: echo "GO_VERSION=$(go version | awk '{ print $3}' | sed 's/^go//')" >> $GITHUB_ENV
      - name: Login to docker
        run: docker login -u thomasgouderps -p ${{ secrets.DOCKER_CD_TOKEN }}
      - name: Release via goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Docker push
        run: docker push thomasgouderps/jupyterhub-istio-proxy-patched:v0.3.3-patch
